In [2]:
arr = [1,2,3,4]

In [3]:
import numpy as np

In [4]:
np.array(arr)

array([1, 2, 3, 4])

In [10]:
np.arange(0, 11, 3)

array([0, 3, 6, 9])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.random.rand(10)

array([0.48082064, 0.27817471, 0.80487137, 0.69178635, 0.30387807,
       0.99636066, 0.07684059, 0.72143993, 0.99441911, 0.14511508])

In [22]:
np.random.rand(2,3)

array([[0.29488705, 0.58293751, 0.47871079],
       [0.07317639, 0.12758307, 0.16203662]])

In [104]:
np.random.randn(3,3)

array([[-0.73997475,  0.98204676, -0.08754887],
       [-0.68305848,  0.31418586, -0.60183026],
       [-0.51989811, -1.54793125, -2.45044181]])

In [24]:
np.random.randint(1, 100, 5)

array([15, 95, 99, 52, 14])

In [27]:
np.random.randint(1, 200, (2,2))

array([[ 14, 142],
       [186, 142]])

In [105]:
np.eye(2,3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0]])

In [107]:
arr = np.eye(3)

In [39]:
arr.astype(int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [113]:
arr = np.random.randint(1, 30, 10)

In [114]:
arr

array([24, 19,  8, 12,  2,  9, 18, 27, 24, 20])

In [116]:
arr.argmax()

np.int64(7)

In [118]:
arr.max()

np.int64(27)

In [117]:
arr.min()

np.int64(2)

In [119]:
arr.argmin()

np.int64(4)

In [52]:
arr

array([22, 25, 23, 20,  9,  6,  4, 16, 24, 13])

In [53]:
arr[1:]

array([25, 23, 20,  9,  6,  4, 16, 24, 13])

In [54]:
arr[:5]

array([22, 25, 23, 20,  9])

In [56]:
arr[0:3] = 100

In [57]:
arr

array([100, 100, 100,  20,   9,   6,   4,  16,  24,  13])

In [58]:
arr[3]

np.int64(20)

In [59]:
arr[3] = 101

In [60]:
arr

array([100, 100, 100, 101,   9,   6,   4,  16,  24,  13])

In [64]:
slice = arr[0:5]

In [65]:
slice[:] = 200

In [66]:
slice

array([200, 200, 200, 200, 200])

In [67]:
arr

array([200, 200, 200, 200, 200,   6,   4,  16,  24,  13])

In [72]:
arr_copy = arr[0:6].copy()

In [69]:
arr_copy

array([200, 200, 200, 200, 200,   6])

In [70]:
arr_copy = 300

In [73]:
arr_copy

array([200, 200, 200, 200, 200,   6])

In [74]:
arr_copy[:] = 300

In [75]:
arr_copy

array([300, 300, 300, 300, 300, 300])

In [76]:
arr

array([200, 200, 200, 200, 200,   6,   4,  16,  24,  13])

In [77]:
arr.clear()

AttributeError: 'numpy.ndarray' object has no attribute 'clear'

In [78]:
arr.fill(0)

In [79]:
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

AttributeError: 'numpy.ndarray' object has no attribute 'empty'

In [82]:
np.empty(arr)

array([], shape=(0, 0, 0, 0, 0, 0, 0, 0, 0, 0), dtype=float64)

In [83]:
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [163]:
arr

array([24, 19,  8, 12,  2,  9, 18, 27, 24, 20])

In [165]:
arr[:6]

array([24, 19,  8, 12,  2,  9])

In [166]:
arr[100]

IndexError: index 100 is out of bounds for axis 0 with size 10

NameError: name 'B' is not defined

In [169]:
%time np.arange(100,100)

CPU times: user 24 μs, sys: 3 μs, total: 27 μs
Wall time: 31.9 μs


array([], dtype=int64)

In [170]:
%ls

Basics.ipynb  numpy.ipynb


In [172]:
np.arange(7,10,2)

array([7, 9])

In [173]:
np.arange(

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [175]:
arr = np.random.randint(1,100,(3,3))

In [176]:
arr

array([[24, 52, 23],
       [28, 91, 87],
       [80, 43, 97]])

In [178]:
arr[0][0] = 25

In [179]:
arr

array([[25, 52, 23],
       [28, 91, 87],
       [80, 43, 97]])

In [181]:
lst = [[1,2],[3,4]]

In [183]:
lst[0,0]

TypeError: list indices must be integers or slices, not tuple

In [185]:
arr[0,0]

np.int64(25)

In [252]:
arr[0:,1:2]

array([[52],
       [91],
       [43]])

In [255]:
arr

array([[25, 52, 23],
       [28, 91, 87],
       [80, 43, 97]])

In [281]:
arr[2:]

array([[80, 43, 97]])

In [282]:
arr1 = np.arange(1,11)

In [292]:
bool_arr1 = arr1 % 2 == 0

In [293]:
arr1[bool_arr1]

array([ 2,  4,  6,  8, 10])

In [296]:
arr1[arr1 % 2 != 0]

array([1, 3, 5, 7, 9])

In [295]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [301]:
arr_2d = np.arange(50).reshape(5,10)

In [302]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [315]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [319]:
arr_2d[2:4,5:7]

array([[25, 26],
       [35, 36]])

In [326]:
arr_2d[3:,7:9]

array([[37, 38],
       [47, 48]])

In [4]:
import numpy as np

In [5]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [7]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [12]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [22]:
mat[4]

array([21, 22, 23, 24, 25])

In [25]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
mat.sum()

np.int64(325)